### ISSUE TITLE
The -css command line option has been replaced with -c in recent versions of pandoc

### ISSUE THREAD

**Issue by krishnakumarg1984** [bk/pdc#1]
Hi, I am trying out `pdc` and so far have had a positive start with it.

There is just one minor thing that I'd like to report here. It looks like the `-css` command-line option has been replaced with `-c`. Here is an example from the pandoc [examples page](https://pandoc.org/demos.html#)

```
wget https://pandoc.org/demo/pandoc.css
pandoc -s --toc -c pandoc.css -A footer.html MANUAL.txt -o example3.html
```

**Comment by bk** [comment]
`-c` is a shortcut option which means the same as `--css`.
